[package]
name = "clever"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.33"
crossterm = "0.27.0"
ratatui = "0.25.0"
unicode-width = "0.1.11"
